name: Request_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.MicrosoftDynamics365.Request/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.MicrosoftDynamics365.Request
      env_var_name_1: CLIENT_ID
      env_var_name_2: CLIENT_SECRET
      env_var_name_3: TENANT_ID
      env_var_name_4: DYNAMICS365_URL
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.CLIENT_ID }}
      env_var_value_2: ${{ secrets.CLIENT_SECRET }}
      env_var_value_3: ${{ secrets.TENANT_ID }}
      env_var_value_4: ${{ secrets.DYNAMICS365_URL }}
